import { useState, useEffect } from "react";
import { Link } from "react-router-dom";
import { Sparkles, Zap, Shield, Image as ImageIcon, Wand2, Heart, Compass } from "lucide-react";
import { motion } from "motion/react";

const features = [
  {
    icon: Wand2,
    title: "Advanced Anime Models",
    description: "State-of-the-art models fine-tuned specifically for anime and manga art styles.",
  },
  {
    icon: Zap,
    title: "Lightning Fast",
    description: "Generate high-resolution images in seconds with our optimized GPU cluster.",
  },
  {
    icon: Shield,
    title: "Private & Secure",
    description: "Your generations and prompts are completely private and secure.",
  },
];

const initialSampleImages = [
  "https://picsum.photos/seed/anime1/400/600",
  "https://picsum.photos/seed/anime2/400/400",
  "https://picsum.photos/seed/anime3/400/500",
  "https://picsum.photos/seed/anime4/400/700",
  "https://picsum.photos/seed/anime5/400/450",
  "https://picsum.photos/seed/anime6/400/550",
];

export default function Home() {
  const [images, setImages] = useState(initialSampleImages);

  useEffect(() => {
    const communityItems = JSON.parse(localStorage.getItem("senpai_community") || "[]");
    if (communityItems.length > 0) {
      const userImages = communityItems.map((item: any) => item.src);
      setImages([...userImages, ...initialSampleImages].slice(0, 8));
    }
  }, []);

  return (
    <div className="flex-1 flex flex-col">
      {/* Hero Section */}
      <section className="relative pt-20 pb-32 overflow-hidden">
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-pink-900/20 via-zinc-950 to-zinc-950 -z-10" />
        
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10 text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-zinc-900/80 border border-zinc-800 text-sm text-zinc-300 mb-8"
          >
            <Sparkles className="w-4 h-4 text-pink-500" />
            <span>Senpai-AI v2.0 is now live</span>
          </motion.div>
          
          <motion.h1
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.1 }}
            className="text-5xl md:text-7xl font-bold tracking-tight mb-6"
          >
            Create Uncensored <br className="hidden md:block" />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-pink-500 via-purple-500 to-indigo-500">
              Anime AI Art
            </span>
          </motion.h1>
          
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.2 }}
            className="text-lg md:text-xl text-zinc-400 max-w-2xl mx-auto mb-10"
          >
            The most advanced AI image generator for anime, manga, and realistic character creation. Bring your imagination to life in seconds.
          </motion.p>
          
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.3 }}
            className="flex flex-col sm:flex-row items-center justify-center gap-4"
          >
            <Link
              to="/create"
              className="w-full sm:w-auto px-8 py-4 rounded-full bg-white text-black font-bold text-lg hover:bg-zinc-200 transition-transform hover:scale-105 active:scale-95 flex items-center justify-center gap-2"
            >
              <Sparkles className="w-5 h-5" />
              Start Creating for Free
            </Link>
            <Link
              to="/explore"
              className="w-full sm:w-auto px-8 py-4 rounded-full bg-zinc-900 text-white font-bold text-lg border border-zinc-800 hover:bg-zinc-800 transition-colors flex items-center justify-center gap-2"
            >
              <Compass className="w-5 h-5" />
              Explore Gallery
            </Link>
          </motion.div>
        </div>
      </section>

      {/* Masonry Gallery Preview */}
      <section className="py-20 bg-zinc-950 border-t border-zinc-900">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold mb-4">Generated by our Community</h2>
            <p className="text-zinc-400">Join thousands of creators making stunning artwork daily.</p>
          </div>
          
          <div className="columns-2 md:columns-3 lg:columns-4 gap-4 space-y-4">
            {images.map((src, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, scale: 0.9 }}
                whileInView={{ opacity: 1, scale: 1 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4, delay: i * 0.1 }}
                className="relative group rounded-xl overflow-hidden bg-zinc-900 break-inside-avoid"
              >
                <img
                  src={src}
                  alt={`Community generation ${i + 1}`}
                  className="w-full h-auto object-cover transition-transform duration-500 group-hover:scale-110"
                  referrerPolicy="no-referrer"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/0 to-black/0 opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex flex-col justify-end p-4">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <div className="w-6 h-6 rounded-full bg-zinc-700" />
                      <span className="text-sm font-medium text-white">Creator</span>
                    </div>
                    <button className="p-2 rounded-full bg-white/10 hover:bg-white/20 backdrop-blur-sm text-white transition-colors">
                      <Heart className="w-4 h-4" />
                    </button>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
          
          <div className="mt-12 text-center">
            <Link
              to="/explore"
              className="inline-flex items-center gap-2 text-pink-500 hover:text-pink-400 font-medium transition-colors"
            >
              View more in Explore <Zap className="w-4 h-4" />
            </Link>
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="py-24 bg-zinc-900/30">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid md:grid-cols-3 gap-8">
            {features.map((feature, i) => {
              const Icon = feature.icon;
              return (
                <motion.div
                  key={i}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.5, delay: i * 0.1 }}
                  className="p-6 rounded-2xl bg-zinc-900/50 border border-zinc-800 hover:border-zinc-700 transition-colors"
                >
                  <div className="w-12 h-12 rounded-xl bg-pink-500/10 flex items-center justify-center mb-6">
                    <Icon className="w-6 h-6 text-pink-500" />
                  </div>
                  <h3 className="text-xl font-bold mb-3">{feature.title}</h3>
                  <p className="text-zinc-400 leading-relaxed">
                    {feature.description}
                  </p>
                </motion.div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-12 border-t border-zinc-900 bg-zinc-950">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col md:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-pink-500" />
            <span className="font-bold text-lg">Senpai-AI</span>
          </div>
          <div className="text-sm text-zinc-500">
            © {new Date().getFullYear()} Senpai-AI. All rights reserved.
          </div>
          <div className="flex items-center gap-6 text-sm font-medium text-zinc-400">
            <a href="#" className="hover:text-white transition-colors">Terms</a>
            <a href="#" className="hover:text-white transition-colors">Privacy</a>
            <a href="#" className="hover:text-white transition-colors">Discord</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
